### ISSUE TITLE
Line breaks in a confirmation dialog

### ISSUE THREAD

**Issue by Takumi-kun** [peopleware/angular-sdk#2]
Line breaks (represented by `\n`) are not translated correctly in the content of the `confirmation-dialog-component`. They appear as a whitespace instead of a line break. Other tags like `<br/>` are not supported either, they just appear as plain text.

Perhaps [this answer on stackoverflow](https://stackoverflow.com/a/56627887) provides the solution, using a global style setting.

This does already work without any settings, however, when using the translate pipe on a `[matToolTip]` property. For example the following label does result in two paragraphs with the translation as shown below.

```html
<label [for]="toggle.buttonId" [matTooltip]="'geo-zone-detail.maintenance-mode-tooltip' | translate">
    {{ 'geo-zone-detail.maintenance-mode' | translate }}
</label>
``` 
```typescript
"geo-zone-detail": {
    "maintenance-mode-tooltip": "When the geo-zone is put in maintenance mode, only administrators have access to it.\n\nSales persons are no longer able to search/view their incentives."
}
```

Therefore, I would expect the `[translate]` property on the `mat-dialog-content` below would work the same way. To no avail, unfortunately.
```html
<mat-dialog-content
    class="mat-typography"
    [translate]="data.bodyKey"
    [translateParams]="data.bodyParams"></mat-dialog-content>
```

**Comment by glenstaes** [comment]
Fixed:

![image](https://github.com/peopleware/angular-sdk/assets/8949285/2784d229-0872-462b-abf5-b1b6a775516f)
